"use client";
import { Lato } from "next/font/google";
import "./globals.css";
import { useEffect } from "react";

const lato = Lato({
  weight: ["100", "300", "400", "700"],
  subsets: ["latin"],
  display: "swap",
});

// export const metadata = {
//   title: 'Royale touche',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  useEffect(() => {
    console.log(window);
    window.dataLayer = window.dataLayer || [];
    function gtag() {
      dataLayer.push(arguments);
    }
    gtag("js", new Date());

    gtag("config", "G-MTKLKTNEJT");

    (function (w, d, s, l, i) {
      w[l] = w[l] || [];
      w[l].push({ "gtm.start": new Date().getTime(), event: "gtm.js" });
      var f = d.getElementsByTagName(s)[0],
        j = d.createElement(s),
        dl = l != "dataLayer" ? "&l=" + l : "";
      j.async = true;
      j.src = "https://www.googletagmanager.com/gtm.js?id=" + i + dl;
      f.parentNode.insertBefore(j, f);
    })(window, document, "script", "dataLayer", "GTM-W6VNSPT6");
  });

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "Royale Touche Plywood",
    url: "https://plywood.royaletouche.com/",
    logo: "https://plywood.royaletouche.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FfinalNavbarLogo.f0efe1b4.png&w=256&q=75",
  };

  const jsonLd2 = {
    "@context": "https://schema.org/",
    "@type": "WebSite",
    name: "Royale Touche Plywood",
    url: "https://plywood.royaletouche.com/",
    potentialAction: {
      "@type": "SearchAction",
      target: "{search_term_string}",
      "query-input": "required name=search_term_string",
    },
  };
  return (
    <html lang="en">
      <head>
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-MTKLKTNEJT"
        ></script>
        <link rel="canonical" href="https://plywood.royaletouche.com/" />
        <link rel="canonical" href="https://plywood.royaletouche.com/blogs/" />
        <link
          rel="canonical"
          href="https://plywood.royaletouche.com/claim-warranty/"
        />
        <link
          rel="canonical"
          href="https://plywood.royaletouche.com/contact-us/"
        />
        <link
          rel="canonical"
          href="https://plywood.royaletouche.com/privacy-policy/"
        />
        <link
          rel="canonical"
          href="https://plywood.royaletouche.com/about-us/"
        />
        <link
          rel="canonical"
          href="https://plywood.royaletouche.com/product/plywood/"
        />
        <link
          rel="canonical"
          href="https://plywood.royaletouche.com/find-store/"
        />
        <link rel="canonical" href="https://plywood.royaletouche.com/faqs/" />
        <link
          rel="canonical"
          href="https://plywood.royaletouche.com/product/blockboard/"
        />
        <link
          rel="canonical"
          href="https://plywood.royaletouche.com/terms-and-condition/"
        />
        <link
          rel="canonical"
          href="https://plywood.royaletouche.com/blogs/5-advantage-why-to-choose-waterproof-plywood/"
        />
        <link
          rel="canonical"
          href="https://plywood.royaletouche.com/blogs/5-tips-on-how-to-maintain-plywood-sheets/"
        />
        <link
          rel="canonical"
          href="https://plywood.royaletouche.com/blogs/7-easy-ways-to-clean-plywood-furniture/"
        />
        <link
          rel="canonical"
          href="https://plywood.royaletouche.com/blogs/types-of-plywood-size-and-what-are-the-difference/"
        />
        <link
          rel="canonical"
          href="https://plywood.royaletouche.com/blogs/101-plywoods-everything-knows-about-plywood/"
        />
        <link
          rel="canonical"
          href="https://plywood.royaletouche.com/blogs/fire-resistant-plywood-things-you-should-know/"
        />
        <link
          rel="canonical"
          href="https://plywood.royaletouche.com/blogs/how-to-choose-best-plywood-for-interiors/"
        />
        <link
          rel="canonical"
          href="https://plywood.royaletouche.com/blogs/how-to-choose-high-quality-plywoods-for-furniture/"
        />
        <link
          rel="canonical"
          href="https://plywood.royaletouche.com/blogs/kitchen-plywood-which-plywood-is-best-for-modular-kitchen/"
        />
        <link
          rel="canonical"
          href="https://plywood.royaletouche.com/blogs/know-everything-about-veneer-plywood/"
        />
        <link
          rel="canonical"
          href="https://plywood.royaletouche.com/blogs/make-your-furniture-strong-using-tremite-resistant-ply/"
        />
        <link
          rel="canonical"
          href="https://plywood.royaletouche.com/blogs/what-is-commercial-plywood/"
        />
      </head>

      <body className={lato.className}>
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-W6VNSPT6"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          ></iframe>
        </noscript>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        ></script>

        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd2) }}
        ></script>
        {children}
      </body>
    </html>
  );
}
